export const theme = {
  colors: {
    primary: '#155C49',
    primaryDark: '#0E4033',
    primaryLight: '#E8F8F3',
    accent: '#C9A84C',
    background: '#FAFAF7',
    surface: '#FFFFFF',
    border: '#E5E7EB',
    borderDark: '#D0D5DD',
    text: '#202425',
    textMuted: '#667085',
    textLight: '#98A2B3',
    danger: '#D92D20',
    dangerLight: '#FEE4E2',
    success: '#027A48',
    successLight: '#ECFDF3',
    warning: '#B54708',
    warningLight: '#FFFAEB',
  },
  typography: {
    fontFamily: {
      regular: 'System',
      medium: 'System',
      bold: 'System',
    },
    sizes: {
      xs: 12,
      sm: 13,
      base: 15,
      lg: 18,
      xl: 22,
      xxl: 28,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
  },
};
